<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class MahasiswaSeeder extends Seeder
{
    public function run(): void
    {
        $mahasiswas = [
            // Cluster Alpha (kelompok_id = 1) - 4 mahasiswa
            [
                'name' => 'Ahmad Rizky Pratama',
                'nim' => '253140707111001',
                'username' => 'ahmad',
                'email' => 'ahmad@students.ub.ac.id',
                'email_student' => 'ahmad@students.ub.ac.id',
                'program_studi' => 'Teknologi Informasi',
                'angkatan' => '2025',
                'nomor_telepon' => '081234560001',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '2006-02-14',
                'jenis_kelamin' => 'Laki-laki',
                'asal_sekolah_jenis' => 'SMA',
                'asal_sekolah_nama' => 'SMA Negeri 1 Malang',
                'jurusan_sekolah' => 'IPA',
                'asal_kota' => 'Malang',
                'alamat_domisili' => 'Jl. Merdeka No.10, Malang',
                'alamat_lengkap' => 'Jl. Merdeka No.10, Kec. Klojen, Kota Malang, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kota_kabupaten' => 'Kota',
                'jalur_masuk' => 'SNBP',
                'deskripsi' => 'Mahasiswa baru yang antusias belajar teknologi',
                'password' => Hash::make('password'),
                'role' => 'mahasiswa',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Putri Anjani',
                'nim' => '253140707111002',
                'username' => 'putri',
                'email' => 'putri@students.ub.ac.id',
                'email_student' => 'putri@students.ub.ac.id',
                'program_studi' => 'Teknologi Informasi',
                'angkatan' => '2025',
                'nomor_telepon' => '081234560002',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2006-06-20',
                'jenis_kelamin' => 'Perempuan',
                'asal_sekolah_jenis' => 'SMA',
                'asal_sekolah_nama' => 'SMA Negeri 3 Yogyakarta',
                'jurusan_sekolah' => 'IPA',
                'asal_kota' => 'Yogyakarta',
                'alamat_domisili' => 'Jl. Pandeglang No.19, Malang',
                'alamat_lengkap' => 'Jl. Pandeglang No.19, Kec. Klojen, Kota Malang, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kota_kabupaten' => 'Kota',
                'jalur_masuk' => 'SNBT',
                'deskripsi' => 'Suka desain danUI/UX',
                'password' => Hash::make('password'),
                'role' => 'mahasiswa',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Fajar Nugroho',
                'nim' => '253140707111003',
                'username' => 'fajar',
                'email' => 'fajar@students.ub.ac.id',
                'email_student' => 'fajar@students.ub.ac.id',
                'program_studi' => 'Teknik Informatika',
                'angkatan' => '2025',
                'nomor_telepon' => '081234560003',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2006-01-28',
                'jenis_kelamin' => 'Laki-laki',
                'asal_sekolah_jenis' => 'SMK',
                'asal_sekolah_nama' => 'SMK Negeri 7 Semarang',
                'jurusan_sekolah' => 'Teknik Komputer dan Jaringan',
                'asal_kota' => 'Semarang',
                'alamat_domisili' => 'Jl. Langsep No.5, Malang',
                'alamat_lengkap' => 'Jl. Langsep No.5, Kec. Klojen, Kota Malang, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kota_kabupaten' => 'Kota',
                'jalur_masuk' => 'Mandiri Vokasi',
                'deskripsi' => 'Tertarik di bidang jaringan dan keamanan siber',
                'password' => Hash::make('password'),
                'role' => 'mahasiswa',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Lestari Wulandari',
                'nim' => '253140707111004',
                'username' => 'lestari',
                'email' => 'lestari@students.ub.ac.id',
                'email_student' => 'lestari@students.ub.ac.id',
                'program_studi' => 'Sistem Informasi',
                'angkatan' => '2025',
                'nomor_telepon' => '081234560004',
                'tempat_lahir' => 'Denpasar',
                'tanggal_lahir' => '2006-09-12',
                'jenis_kelamin' => 'Perempuan',
                'asal_sekolah_jenis' => 'SMA',
                'asal_sekolah_nama' => 'SMA Negeri 1 Denpasar',
                'jurusan_sekolah' => 'IPS',
                'asal_kota' => 'Denpasar',
                'alamat_domisili' => 'Jl. Sawojajar No.22, Malang',
                'alamat_lengkap' => 'Jl. Sawojajar No.22, Kec. Kedungkandang, Kota Malang, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kota_kabupaten' => 'Kota',
                'jalur_masuk' => 'SNBP',
                'deskripsi' => 'Mahasiswa aktif organisasi dan sosial',
                'password' => Hash::make('password'),
                'role' => 'mahasiswa',
                'email_verified_at' => now(),
            ],
            // Cluster Bravo (kelompok_id = 2) - 4 mahasiswa
            [
                'name' => 'Bayu Saputra',
                'nim' => '253140707111005',
                'username' => 'bayu',
                'email' => 'bayu@students.ub.ac.id',
                'email_student' => 'bayu@students.ub.ac.id',
                'program_studi' => 'Teknik Informatika',
                'angkatan' => '2025',
                'nomor_telepon' => '081234560005',
                'tempat_lahir' => 'Batam',
                'tanggal_lahir' => '2006-04-08',
                'jenis_kelamin' => 'Laki-laki',
                'asal_sekolah_jenis' => 'SMK',
                'asal_sekolah_nama' => 'SMK Negeri 2 Batam',
                'jurusan_sekolah' => 'Rekayasa Perangkat Lunak',
                'asal_kota' => 'Batam',
                'alamat_domisili' => 'Jl. Semeru No.8, Malang',
                'alamat_lengkap' => 'Jl. Semeru No.8, Kec. Lowokwaru, Kota Malang, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kota_kabupaten' => 'Kota',
                'jalur_masuk' => 'Mandiri UB',
                'deskripsi' => 'Hobby coding dan open source',
                'password' => Hash::make('password'),
                'role' => 'mahasiswa',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Citra Ayu Lestari',
                'nim' => '253140707111006',
                'username' => 'citra',
                'email' => 'citra@students.ub.ac.id',
                'email_student' => 'citra@students.ub.ac.id',
                'program_studi' => 'Teknologi Informasi',
                'angkatan' => '2025',
                'nomor_telepon' => '081234560006',
                'tempat_lahir' => 'Pontianak',
                'tanggal_lahir' => '2006-08-25',
                'jenis_kelamin' => 'Perempuan',
                'asal_sekolah_jenis' => 'SMA',
                'asal_sekolah_nama' => 'SMA Negeri 10 Pontianak',
                'jurusan_sekolah' => 'IPA',
                'asal_kota' => 'Pontianak',
                'alamat_domisili' => 'Jl. Borobudur No.12, Malang',
                'alamat_lengkap' => 'Jl. Borobudur No.12, Kec. Sukun, Kota Malang, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kota_kabupaten' => 'Kota',
                'jalur_masuk' => 'SNBP',
                'deskripsi' => 'Suka data science dan machine learning',
                'password' => Hash::make('password'),
                'role' => 'mahasiswa',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Dwi Kurniawan',
                'nim' => '253140707111007',
                'username' => 'dwi',
                'email' => 'dwi@students.ub.ac.id',
                'email_student' => 'dwi@students.ub.ac.id',
                'program_studi' => 'Sistem Informasi',
                'angkatan' => '2025',
                'nomor_telepon' => '081234560007',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2006-12-03',
                'jenis_kelamin' => 'Laki-laki',
                'asal_sekolah_jenis' => 'SMA',
                'asal_sekolah_nama' => 'SMA Negeri 1 Makassar',
                'jurusan_sekolah' => 'IPS',
                'asal_kota' => 'Makassar',
                'alamat_domisili' => 'Jl. Raya Tlogomas No.7, Malang',
                'alamat_lengkap' => 'Jl. Raya Tlogomas No.7, Kec. Lowokwaru, Kota Malang, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kota_kabupaten' => 'Kota',
                'jalur_masuk' => 'SNBT',
                'deskripsi' => 'Minat di bidang bisnis digital dan startup',
                'password' => Hash::make('password'),
                'role' => 'mahasiswa',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Eka Putri Rahayu',
                'nim' => '253140707111008',
                'username' => 'eka',
                'email' => 'eka@students.ub.ac.id',
                'email_student' => 'eka@students.ub.ac.id',
                'program_studi' => 'Teknologi Informasi',
                'angkatan' => '2025',
                'nomor_telepon' => '081234560008',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '2006-05-17',
                'jenis_kelamin' => 'Perempuan',
                'asal_sekolah_jenis' => 'SMK',
                'asal_sekolah_nama' => 'SMK Negeri 1 Palembang',
                'jurusan_sekolah' => 'Multimedia',
                'asal_kota' => 'Palembang',
                'alamat_domisili' => 'Jl. Karang Menjangan No.18, Malang',
                'alamat_lengkap' => 'Jl. Karang Menjangan No.18, Kec. Klojen, Kota Malang, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kota_kabupaten' => 'Kota',
                'jalur_masuk' => 'Mandiri Vokasi',
                'deskripsi' => 'Kreatif di bidang desain grafis dan video editing',
                'password' => Hash::make('password'),
                'role' => 'mahasiswa',
                'email_verified_at' => now(),
            ],
            // Cluster Charlie (kelompok_id = 3) - 4 mahasiswa
            [
                'name' => 'Gilang Ramadhan',
                'nim' => '253140707111009',
                'username' => 'gilang',
                'email' => 'gilang@students.ub.ac.id',
                'email_student' => 'gilang@students.ub.ac.id',
                'program_studi' => 'Teknik Informatika',
                'angkatan' => '2025',
                'nomor_telepon' => '081234560009',
                'tempat_lahir' => 'Banjarmasin',
                'tanggal_lahir' => '2006-10-30',
                'jenis_kelamin' => 'Laki-laki',
                'asal_sekolah_jenis' => 'SMA',
                'asal_sekolah_nama' => 'SMA Negeri 2 Banjarmasin',
                'jurusan_sekolah' => 'IPA',
                'asal_kota' => 'Banjarmasin',
                'alamat_domisili' => 'Jl. Sumpah Pemuda No.3, Malang',
                'alamat_lengkap' => 'Jl. Sumpah Pemuda No.3, Kec. Klojen, Kota Malang, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kota_kabupaten' => 'Kota',
                'jalur_masuk' => 'SNBP',
                'deskripsi' => 'Game developer dan Unity enthusiast',
                'password' => Hash::make('password'),
                'role' => 'mahasiswa',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Hana Permata Sari',
                'nim' => '253140707111010',
                'username' => 'hana',
                'email' => 'hana@students.ub.ac.id',
                'email_student' => 'hana@students.ub.ac.id',
                'program_studi' => 'Sistem Informasi',
                'angkatan' => '2025',
                'nomor_telepon' => '081234560010',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2006-07-22',
                'jenis_kelamin' => 'Perempuan',
                'asal_sekolah_jenis' => 'SMA',
                'asal_sekolah_nama' => 'SMA Negeri 4 Medan',
                'jurusan_sekolah' => 'IPS',
                'asal_kota' => 'Medan',
                'alamat_domisili' => 'Jl. Aminah Sayuti No.14, Malang',
                'alamat_lengkap' => 'Jl. Aminah Sayuti No.14, Kec. Klojen, Kota Malang, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kota_kabupaten' => 'Kota',
                'jalur_masuk' => 'SNBT',
                'deskripsi' => 'Tertarik di UI/UX Research dan Human-Computer Interaction',
                'password' => Hash::make('password'),
                'role' => 'mahasiswa',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Irfan Hakim',
                'nim' => '253140707111011',
                'username' => 'irfan',
                'email' => 'irfan@students.ub.ac.id',
                'email_student' => 'irfan@students.ub.ac.id',
                'program_studi' => 'Teknologi Informasi',
                'angkatan' => '2025',
                'nomor_telepon' => '081234560011',
                'tempat_lahir' => 'Manado',
                'tanggal_lahir' => '2006-03-05',
                'jenis_kelamin' => 'Laki-laki',
                'asal_sekolah_jenis' => 'SMK',
                'asal_sekolah_nama' => 'SMK Negeri 1 Manado',
                'jurusan_sekolah' => 'Teknik Komputer dan Jaringan',
                'asal_kota' => 'Manado',
                'alamat_domisili' => 'Jl. Trunojoyo No.20, Malang',
                'alamat_lengkap' => 'Jl. Trunojoyo No.20, Kec. Klojen, Kota Malang, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kota_kabupaten' => 'Kota',
                'jalur_masuk' => 'Mandiri UB',
                'deskripsi' => 'Cloud computing dan DevOps enthusiast',
                'password' => Hash::make('password'),
                'role' => 'mahasiswa',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Jingga Larasati',
                'nim' => '253140707111012',
                'username' => 'jingga',
                'email' => 'jingga@students.ub.ac.id',
                'email_student' => 'jingga@students.ub.ac.id',
                'program_studi' => 'Teknik Informatika',
                'angkatan' => '2025',
                'nomor_telepon' => '081234560012',
                'tempat_lahir' => 'Bali',
                'tanggal_lahir' => '2006-11-18',
                'jenis_kelamin' => 'Perempuan',
                'asal_sekolah_jenis' => 'SMA',
                'asal_sekolah_nama' => 'SMA Negeri 1 Denpasar',
                'jurusan_sekolah' => 'IPA',
                'asal_kota' => 'Denpasar',
                'alamat_domisili' => 'Jl. KA Tarmidi No.25, Malang',
                'alamat_lengkap' => 'Jl. KA Tarmidi No.25, Kec. Klojen, Kota Malang, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kota_kabupaten' => 'Kota',
                'jalur_masuk' => 'SNBP',
                'deskripsi' => 'Frontend developer dengan fokus React dan Vue.js',
                'password' => Hash::make('password'),
                'role' => 'mahasiswa',
                'email_verified_at' => now(),
            ],
        ];

        foreach ($mahasiswas as $mhs) {
            User::create($mhs);
        }
    }
}
